project_name: db1000n
builds:
  - id: db1000n
    env:
      - CGO_ENABLED=0
    dir: .
    main: .
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - netbsd
      - openbsd
      - dragonfly
      - aix
      - illumos
      - solaris
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
      - "mips"
      - "mips64"
      - "mips64le"
      - "mipsle"
      - "riscv64"
      - "s390x"
    gomips:
      - hardfloat
      - softfloat
    flags:
      - -tags=encrypted
    ldflags:
      - -s -w
      - -extldflags "-static"
      - -X github.com/Arriven/db1000n/src/utils/ota.Version={{ .Version }}
      - -X github.com/Arriven/db1000n/src/utils.EncryptionKeys={{ .Env.ENCRYPTION_KEYS }}
      - -X github.com/Arriven/db1000n/src/job/config.DefaultConfig={{ .Env.DEFAULT_CONFIG_VALUE }}
      - -X github.com/Arriven/db1000n/src/job.DefaultConfigPathCSV={{ .Env.DEFAULT_CONFIG_PATH }}
archives:
  - id: default
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    builds:
      - db1000n
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
