project_name: db1000n
builds:
  - id: db1000n
    env:
      - CGO_ENABLED=0
    dir: .
    main: .
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - netbsd
      - openbsd
      - dragonfly
      - aix
      - illumos
      - solaris
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    flags:
      - -tags=encrypted
    ldflags:
      - -s -w
      - -extldflags "-static"
      - -X github.com/Arriven/db1000n/src/utils/ota.Version={{ .Version }}
archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - db1000n
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
