jobs:
  - type: packetgen
    args:
      connection:
        type: net
        args:
          protocol: "tcp"
          address: "localhost:1234"
          tls_config:
            insecure_skip_verify: true
      packet:
        payload:
          type: raw
          data:
            payload: "test"
