jobs:
  - type: packetgen
    args:
      connection:
        type: net
        args:
          protocol: "udp"
          address: "localhost:1234"
      packet:
        payload:
          type: raw
          data:
            payload: "test"
