name: goreleaser

on:
  push:
    tags: ["**"]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENCRYPTION_KEYS: ${{ secrets.ENCRYPTION_KEYS }}
          CA_PATH_VALUE: ${{ secrets.PROMETHEUS_ROOT_CA }}
          PROMETHEUS_BASIC_AUTH: ${{ secrets.PROMETHEUS_BASIC_AUTH }}
          DEFAULT_CONFIG_VALUE: ${{ secrets.DEFAULT_CONFIG }}
          DEFAULT_CONFIG_PATH: ${{ secrets.DEFAULT_CONFIG_PATH }}
