name: Test install.sh

on:
  push:
    branches:
      - "main"
    paths:
      - 'install.sh'
      - '.github/workflows/test-installer.yaml'

jobs:
  ubuntu-mac-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
      - name: Installer
        run: ./install.sh
  windows-test:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Installer
        run: ./install.sh
